name: UI_Staging_Parallel_Execution
on: workflow_dispatch
jobs:
  ParallelExecution1-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test-stage-ui:addToCartOnly

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome Test Report - 1
          path: cypress/reports/html      

  ParallelExecution2-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test-stage-ui:registrationOnly

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome Test Report - 2
          path: cypress/reports/html